Nyooy/Controllers/ErrorHistoryController.cs
using Nyooy.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Nyooy.Controllers
{
    [SuperAdminSessionCheck]
    public class ErrorHistoryController : Controller
    {
        private db_nyooyEntities _context;
        private db_nyooyEntities _contextError;

        public ErrorHistoryController()
        {
            _context = new db_nyooyEntities();
            _contextError = new db_nyooyEntities();
        }
        // GET: ErrorHistory
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult Getdata()
        {
            long id_courier = (long)Session["id"];
            _context.Configuration.ProxyCreationEnabled = false;

            //NOTE : STATUS ORDER SHOULD BE 'ON DELIVERY'
            var dbErrorLog = _context.tbl_log_history_error.ToList();

            return Json(dbErrorLog, JsonRequestBehavior.AllowGet);
        }
    }
}

Nyooy/Views/ErrorHistory/Index.cshtml
@{
    ViewBag.Title = "Error History";
}

<div class="main-content-container container-fluid px-4">
    <div class="page-header row no-gutters py-4">
        <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
            <span class="text-uppercase page-subtitle">Log History</span>
            <h3 class="page-title">Error History</h3>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="card card-small mb-4">
                <div class="card-header border-bottom">
                    <h6 class="m-0">Error History</h6>
                </div>
                <div class="card-body p-0 pb-3 text-center">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item p-3">
                            <div class="form-row m-4">
                                <div class="form-group col-md-12">

                                    <table id="table_id" class="display" width="100%">
                                        <thead>
                                            <tr>
                                                <th rowspan="1">No</th>
                                                <th rowspan="1">Name</th>
                                                <th rowspan="1">Error Message</th>
                                                <th rowspan="1">Error Position</th>
                                                <th rowspan="1">Error Date</th>
                                            </tr>
                                        </thead>
                                    </table>

                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    var dataTable = $('#table_id').DataTable();

    $.ajax({
            type: 'GET',
            url: '@Url.Action("Getdata", "ErrorHistory")',
            data: { get_param: 'value' },
            dataType: 'json',
            success: function (data) {
                console.log(data[0].id);
                for (var i = 0; i < data.length; i++) {

                    var dateString = data[i].error_date.substr(6);
                    var currentTime = new Date(parseInt(dateString));
                    var month = currentTime.getMonth() + 1;
                    var day = currentTime.getDate();
                    var year = currentTime.getFullYear();
                    var hours = currentTime.getHours();
                    var minute = currentTime.getMinutes();
                    var second = currentTime.getSeconds();

                    if (hours < 10) {
                        hours = "0" + hours;
                    }

                    if (minute < 10) {
                        minute = "0" + minute;
                    }

                    if (second < 10) {
                        second = "0" + second;
                    }

                    var date = day + "/" + month + "/" + year + " " + hours + ":" + minute + ":" + second;
                    //alert(date);

                    dataTable.row.add([
                        i + 1,
                        data[i].user_name,
                        data[i].error_message,
                        data[i].error_position,
                        date
                    ]).draw(false);

                }

            }
        });

</script>