Nyooy/Controllers/AdminController.cs
using Newtonsoft.Json;
using Nyooy.Models;
using Nyooy.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.SqlServer;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Nyooy.Controllers
{
    [AdminSessionCheck]
    public class AdminController : Controller
    {
        private db_nyooyEntities _context;
        private db_nyooyEntities _contextError;

        public AdminController()
        {
            _context = new db_nyooyEntities();
            _contextError = new db_nyooyEntities();
        }

        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        public string GetData()
        {
            var dbTotalProduct = _context.tbl_product.Where(p => p.is_deleted == 0).Count().ToString();
            var dbTotalReviews = _context.tbl_review.Count().ToString();
            var dbTotalUsers = _context.tbl_user.Where(u => u.role == "user").Count().ToString();
            var dbTotalStaff = _context.tbl_user.Where(u => u.role != "user").Count().ToString();
            var dbProductSales = (from d in
                                    (from d in _context.tbl_detail_order
                                     where
                                       d.tbl_order.order_status == "Success"
                                     select new
                                     {
                                         d.qty,
                                         Dummy = "x"
                                     })
                                  group d by new { d.Dummy } into g
                                  select new
                                  {
                                      sales = (int?)g.Sum(p => p.qty)
                                  }).FirstOrDefault();

            var dbLast30days = (from d in _context.tbl_detail_order
                                where
                                  d.tbl_order.order_status == "Success" &&
                                  d.tbl_order.order_date >= SqlFunctions.DateAdd("month", -1, SqlFunctions.GetDate())
                                group new { d.tbl_order, d } by new
                                {
                                    Column1 = DbFunctions.TruncateTime(d.tbl_order.order_date)
                                } into g
                                select new
                                {
                                    Tanggal_Transaksi = g.Key.Column1,
                                    Column1 = (int?)g.Sum(p => p.d.total_price)
                                }).ToList();
            var data = new
            {
                productSales = dbProductSales.sales,
                totalProduct = dbTotalProduct,
                totalReview = dbTotalReviews,
                totalUsers = dbTotalUsers,
                totalStaff = dbTotalStaff,
                a = dbLast30days
            };
            return JsonConvert.SerializeObject(data);
        }
    }
}

Nyooy/Controllers/ConfigController.cs
using Nyooy.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Nyooy.Controllers
{
    public class ConfigController : Controller
    {
        db_nyooyEntities _context;
        private ErrorLog _err;
        public ConfigController()
        {
            _context = new db_nyooyEntities();
            _err = new ErrorLog();
        }

        [SuperAdminSessionCheck]
        // GET: Config
        public ActionResult Index()
        {
            var db = _context.tbl_config.Where(c => c.id == 1).SingleOrDefault();
            return View(db);
        }

        [HttpPost]
        public ActionResult Save(tbl_config config)
        {
            dynamic name = Session["name"];
            var db = _context.tbl_config.Where(c => c.id == config.id).SingleOrDefault();

            using (var save = _context.Database.BeginTransaction())
            {
                try
                {

                    if (db != null)
                    {
                        db.time_get_location = config.time_get_location;
                    }

                    _context.SaveChanges();
                    save.Commit();

                    ViewBag.Success = "Update Success!";

                }
                catch (Exception e)
                {
                    _err.Save(name, e.Message, "Submit Form Setting");
                    save.Rollback();
                }

                return View("Index");
            }
        }
    }
}

Nyooy/Views/Config/Index.cshtml
@model Nyooy.Models.tbl_config
@{
    ViewBag.Title = "Index";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<div class="main-content-container container-fluid px-4">
    <!-- Page Header -->
    <div class="page-header row no-gutters py-4">
        <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
            <span class="text-uppercase page-subtitle">Dashboard</span>
            <h3 class="page-title">Settings</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-10 mb-4">
            <div class="card card-small mb-4">
                <div class="card-header border-bottom">
                    <a href="@Url.Action("Index", "Admin")">
                        <span style="font-size:17px; display:inline-block;" class="fa">&#xf060;</span>
                    </a>
                    <h6 class="m-0 m-lg-3" style="display:inline-block;">Update Get Location Delivery Time</h6>
                </div>
                @using (Html.BeginForm("Save", "Config"))
                {
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item p-3">
                            <!-- Normal Buttons -->

                            <div class="form-row">
                                <div class="form-group col-md-12">
                                    @*@Html.LabelFor(c => c.Product.price, "Price")*@
                                    @Html.LabelFor(c => c.time_get_location, "Time")
                                    <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text" id="basic-addon1">Milisecond </span>
                                        </div>
                                        @Html.TextBoxFor(c => c.time_get_location, new { @class = "form-control", @type = "number", @placeholder = "10000" })
                                    </div>
                                </div>
                            </div>

                            @Html.HiddenFor(c => c.id)

                            <div class="row" style="justify-content: flex-end;">
                                <a href="@Url.Action("Index", "Admin")">
                                    <div class="btn btn-danger" style="margin-left: 5px;margin-right: 5px;">
                                        Cancel
                                    </div>
                                </a>
                                <button type="submit" class="btn btn-accent" style="margin-left: 5px;margin-right: 5px;">Submit</button>

                            </div>
                        </li>
                    </ul>
                }
            </div>
        </div>
    </div>
</div>